name: PR

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: microsoft/setup-msbuild@v1.0.0

      - name: Patch PR build version
        shell: powershell
        run: |
          $version = GitVersion /output json /updateassemblyinfo "Blish HUD/Properties/AssemblyVersionInfo.cs" /ensureassemblyinfo
          Write-Output $version
          $version = $version | ConvertFrom-Json
          $nuget = $version.SemVer
          Write-Output "Assembly version: $($version.AssemblySemVer)"
          Write-Output "Assembly file version: $($version.AssemblySemFileVer)"
          Write-Output "Informational version: $($version.InformationalVersion)"
          Write-Output "NuGet version: $nuget"
          echo "::set-env name=VERSION::$nuget"

      - name: Run msbuild
        run: msbuild -p:Configuration=Release -p:VERSIONED_BUILD=$env:VERSION
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: BlishHUD.${{ env.VERSION }}
          path: Blish HUD/bin/x64/Release/net472
